### ISSUE TITLE
ImageIO Exception.

### ISSUE THREAD

**Issue by FabioCaue** [ItsMeAlves/Genius#1]
javax.imageio.IIOException: Can't read input file!
    at javax.imageio.ImageIO.read(ImageIO.java:1301)
    at home.genius.gui.GraphicInterface.<init>(GraphicInterface.java:40)
    at home.genius.Game.main(Game.java:18)
Exception in thread "main" java.lang.NullPointerException
    at javax.swing.ImageIcon.<init>(ImageIcon.java:240)
    at home.genius.gui.GraphicInterface.setImageTo(GraphicInterface.java:60)
    at home.genius.gui.GraphicInterface.<init>(GraphicInterface.java:44)
    at home.genius.Game.main(Game.java:18)

Falta o arquivo image.png? Não sei, poderia ajudar. Estou tentando aprender com seu código.

**Comment by limaagabriel** [comment]
Olá! Pelo que me lembro a imagem está ai, mas talvez eu tenha desorganizado tudo kk Vou dar uma olhada e atualizo assim que puder. E é bom saber que meu código está ajudando alguém kk se houver dúvidas, fique a vontade para perguntar

**Comment by FabioCaue** [comment]
Nem brinca =) seu código ficou muito legal e está ajudando pra caramba!
É um trabalho que estou fazendo, você vai ser devidamente citado, ai vou puxar seu código pro meu perfil e por os usos e tudo mais. =D
Estou meio perdido no uso da ferramente GitHub ainda mas vai ficar direitinho haha.
Obrigado.

**Comment by limaagabriel** [comment]
Bom que posso ajudar kk Boa sorte no seu trabalho! Bom, sobre a exception que apareceu ai, corrigi o erro. Antes esperava que a imagem do jogo estivesse na pasta de imagens do sistema, quando estava no diretório do projeto. Então, já foi corrigido! Dúvidas, só perguntar.

**Comment by FabioCaue** [comment]
Valeu mesmo!!! Se é muito gente boa!!!
Closing issue!
